version: '3.7'
services:
  backend:
    container_name: dt-back-dev
    image: dt-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    volumes:
      - "./src:/usr/src/app/src"
    networks:
      - dailytrends_back
    depends_on:
      - db
    command: sh -c "./wait-for db:27017 -- npm run dev"
  db:
    container_name: dt-db-dev
    image: mongo:4.0
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DEV_DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DEV_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - "data:/data/db"
    networks:
      - dailytrends_back
volumes:
  data: {}
networks:
  dailytrends_back:
    name: dailytrends
